version: "3.2"
services:
  flip-eth-a:
    build: .
    image: makerdao/auction-keeper
    container_name: flip-eth-a
    working_dir: /opt/keeper/flip-eth-a/
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/env/:/opt/keeper/env/
      - $PWD/flip/eth-a/:/opt/keeper/flip-eth-a/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ./flip-eth-a.sh model-eth.sh
  flip-bat-a:
    build: .
    image: makerdao/auction-keeper
    container_name: flip-bat-a
    working_dir: /opt/keeper/flip-bat-a/
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/env/:/opt/keeper/env/
      - $PWD/flip/bat-a/:/opt/keeper/flip-bat-a/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ./flip-bat-a.sh model-bat.sh
  flip-usdc-a:
    build: .
    image: makerdao/auction-keeper
    container_name: flip-usdc-a
    working_dir: /opt/keeper/flip-usdc-a/
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/env/:/opt/keeper/env/
      - $PWD/flip/usdc-a/:/opt/keeper/flip-usdc-a/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ./flip-usdc-a.sh model-usdc.sh
  flop:
    build: .
    image: makerdao/auction-keeper
    container_name: flop
    working_dir: /opt/keeper/flop/
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/env/:/opt/keeper/env/
      - $PWD/flop/:/opt/keeper/flop/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ./flop.sh model-mkr.sh
  parity:
    image: parity/parity
    restart: unless-stopped
    volumes:
      - ~/.local/share/io.parity.ethereum/docker/:/home/parity/.local/share/io.parity.ethereum/
    ports:
      - 8545:8545
      - 30303:30303
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: [
      "--warp",
      "--warp-barrier", "8928152",
      "--jsonrpc-interface", "all",
      "--jsonrpc-port", "8545",
      "--mode", "active",
      "--num-verifiers", "8",
      "--scale-verifiers",
      "--no-color",
      "--no-ipc",
      "--no-ws",
      "--min-peers=25",
      "--max-peers=50",
      "--no-ancient-blocks"
    ]
